-- ── Report generation infrastructure ─────────────────────────────────────────
-- Tracks generated report files; actual files live in the 'reports' storage bucket.

CREATE TABLE IF NOT EXISTS reports (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  report_type      TEXT        NOT NULL CHECK (report_type IN ('portfolio_summary','holdings','performance','transactions')),
  format           TEXT        NOT NULL CHECK (format IN ('csv','xlsx','pdf')),
  status           TEXT        NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','processing','ready','failed')),
  file_path        TEXT,
  file_size_bytes  BIGINT,
  error_message    TEXT,
  date_range_start DATE,
  date_range_end   DATE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at       TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '24 hours'
);

CREATE INDEX IF NOT EXISTS reports_user_id_created_at_idx ON reports (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS reports_expires_at_idx          ON reports (expires_at) WHERE status = 'ready';

-- ── Row Level Security ────────────────────────────────────────────────────────

ALTER TABLE reports ENABLE ROW LEVEL SECURITY;

-- Users can see and manage only their own reports
CREATE POLICY "reports_select_own"
  ON reports FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "reports_insert_own"
  ON reports FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "reports_update_own"
  ON reports FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "reports_delete_own"
  ON reports FOR DELETE
  USING (auth.uid() = user_id);

-- ── Storage bucket ────────────────────────────────────────────────────────────
-- The 'reports' bucket is private; signed URLs are generated by the edge function.

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'reports',
  'reports',
  false,
  52428800,  -- 50 MB
  ARRAY[
    'text/csv',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/pdf'
  ]
)
ON CONFLICT (id) DO NOTHING;

-- Storage RLS: users can only access files under their own user_id prefix
CREATE POLICY "reports_storage_select_own"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'reports' AND auth.uid()::text = (storage.foldername(name))[1]);

CREATE POLICY "reports_storage_insert_own"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'reports' AND auth.uid()::text = (storage.foldername(name))[1]);

CREATE POLICY "reports_storage_delete_own"
  ON storage.objects FOR DELETE
  USING (bucket_id = 'reports' AND auth.uid()::text = (storage.foldername(name))[1]);

-- ── Cleanup of expired reports (runs via pg_cron) ─────────────────────────────
-- Schedule: daily at 03:00 UTC.  Requires pg_cron extension to be enabled.
-- The cron job deletes expired records; storage files are purged by the edge function or a separate trigger.

CREATE OR REPLACE FUNCTION cleanup_expired_reports()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Remove storage objects for expired, ready reports
  DELETE FROM storage.objects
  WHERE bucket_id = 'reports'
    AND name IN (
      SELECT file_path FROM reports
      WHERE status = 'ready' AND expires_at < NOW()
    );

  -- Remove the report records themselves
  DELETE FROM reports WHERE expires_at < NOW();
END;
$$;

SELECT cron.schedule(
  'cleanup-expired-reports',
  '0 3 * * *',
  'SELECT cleanup_expired_reports()'
) WHERE EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron');
